models/Task.php
<?php

namespace app\models;

use Yii;
require_once dirname(__DIR__).'/parser.php';

/**
 * This is the model class for table "task".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $begin
 * @property string $body
 * @property string $end
 * @property string $result
 * @property string $extra
 * @property integer $category_id
 * @property integer $checktype
 *
 * @property Category $category
 * @property UserTask[] $userTasks
 */
class Task extends \yii\db\ActiveRecord
{
    
    const ITERATION_COUNT = 20;
    const EXECUTION_TIME = 15;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'task';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'category_id'], 'required'],
            [['description', 'begin', 'body', 'end', 'result', 'extra'], 'string'],
            [['category_id', 'checktype'], 'integer'],
            [['name', 'result'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название задачи',
            'description' => 'Описание задачи',
            'begin' => 'Начало программы',
            'body' => 'Тело программы',
            'end' => 'Конец программы',
            'result' => 'Ответ',
            'extra' => 'Extra',
            'category_id' => 'Категория',
            'checktype' => 'Тип проверки'
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserTasks()
    {
        return $this->hasMany(UserTask::className(), ['task_id' => 'id']);
    }
    
    //Запуск программы на компиляторе
    static function run($code){
        $filename = Yii::$app->basePath . '/runtime/' . date('Ymd_H_i_s');
        $res_file = Yii::$app->basePath . '/runtime/info.txt';
        $compile = '';
        $result = '';
        $compile_res = -1;
        if (file_exists($res_file)) {
            file_put_contents($res_file, '');
            if (file_put_contents($filename . '.c', $code)) {

                $descriptorspec = array(
                    0 => array("pipe", "r"), // stdin - канал, из которого дочерний процесс будет читать
                    1 => array("pipe", "w"), // stdout - канал, в который дочерний процесс будет записывать 
                    2 => array("file", $res_file, "a") // stderr - файл для записи
                );
                $process = proc_open("gcc $filename.c -o $filename", $descriptorspec, $pipes);

                if (is_resource($process)) { 
                    $compile_res = proc_close($process);
                    $compile = file_get_contents($res_file); 
                    //сохраняем результат в отдельном файле                    
                    //file_put_contents($filename . '_info.txt', $compile);
                }
                if ($compile_res == 0)
                    $result = shell_exec('timeout '.Task::EXECUTION_TIME.' '.$filename);
                
                //Удаляем временные файлы
                if(file_exists($filename))
                    unlink ($filename);
                if(file_exists($filename.'.c'))
                    unlink ($filename.'.c');
                if(file_exists($filename.'_info.txt'))
                    unlink ($filename. '_info.txt');                
            } else
                $result = "error";
        } else
            Yii::$app->session->setFlash('danger', "<strong>Компиляция не возможна.</strong> Файл $res_file не существует.");
        return ['compile' => $compile, 'compile_res' => $compile_res, 'result' => $result];
    }
    
    //Перебирает переменные
    public function check($code = null){
        if($code == null){
            $code = $this->begin.$this->body.$this->end;
            $origin = true;            
        }
        else
            $origin = false;
        
        $vars = json_decode($this->extra, true);
        $result = [];
        for($iter=0; $iter<Task::ITERATION_COUNT; $iter++){
            $iter_res = [];
            $iter_res['input'] = '';
            if(!$origin)
                $origin_code = $this->begin.$this->body.$this->end;
            foreach($vars['varname'] as $i => $var){
                $params = explode(";", $vars['varparam'][$i]);
                $val = rand($params[0],$params[1]);
                $var = trim($var);  
                $iter_res['input'] = $iter_res['input'] . $var.'='.$val.'; ';
                $code = preg_replace("/$var\s*=\s*-*\s*\d+;/", "$var=$val;", $code);     
                if(!$origin)
                    $origin_code = preg_replace("/$var\s*=\s*-*\s*\d+;/", "$var=$val;", $origin_code);  
            }
            $iter_res['code'] = $code;
            if(!$origin)
                $iter_res['origin_out'] = Task::run($origin_code);
            $iter_res['output'] = Task::run($code);
            if(!$origin){
                $iter_res['decided'] = false;
                if(strpos($iter_res['output']['result'], $iter_res['origin_out']['result'])!==false)
                    $iter_res['decided'] = true;
            }
            $result[] = $iter_res;
        }
        return $result;
        
    }
    public function beforeSave($insert) {
        if(isset($_POST['varname'])){
            $vars = [
                'varname' => $_POST['varname'],
                'vartype' => $_POST['vartype'],
                'varparam' => $_POST['varparam'],
            ];
            $this->extra = json_encode($vars);
        }
        return parent::beforeSave($insert);
    }
    public function getChecktypes(){
        return [
            0 => 'Проверка с ответом',
            1 => 'Перебор переменных и сравнение',
        ];
    }
    public static function getTree($body){
        $l = new \Lexer(); 
        $l->code = $body;        
        $tokens = $l->getTokens();
        $p = new \Parser();
        $p->tokens = $tokens;
        return $p->parse();        
    }
    public function getUserTask(){
        return UserTask::findOne(['task_id' => $this->id, 'user_id' => Yii::$app->user->id]);
    }
}

controllers/TaskController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Task;
use app\models\UserTask;
use app\models\TaskSearch;
use webvimark\modules\UserManagement\models\User;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaskController implements the CRUD actions for Task model.
 */
class TaskController extends Controller {

    public $defaultAction = 'list';
    public $studentActions = ['list', 'decide'];
    public $adminActions = ['index', 'test', 'view', 'check', 'create', 'delete', 'update', 'saveresult', 'student', 'students', 'test-student-task'];

    public function behaviors() {
        return [
//            'ghost-access' => [
//                'class' => 'webvimark\modules\UserManagement\components\GhostAccessControl',
//            ],
            'verbs'        => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Task models.
     * @return mixed
     */
    public function actionIndex() {

        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
                    'searchModel'  => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Task model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        return $this->render('view', [
                    'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Task model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate() {
        $model = new Task();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            $model->begin = "#include <stdlib.h>
#include <stdio.h>
int main(){";
            $model->end = "return 0;
}";
            return $this->render('create', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Task model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Task model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    public function actionList() {
        $searchModel = new TaskSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('list', [
                    'searchModel'  => $searchModel,
                    'dataProvider' => $dataProvider,
        ]);
    }

    public function actionTest($id) {
        $model = $this->findModel($id);
        $code = $model->begin . $model->body . $model->end;
        $res = Task::run($code);
        return $this->render('test', \yii\helpers\ArrayHelper::merge(['model' => $model], $res));
    }

    public function actionTree($id) {
        $model = $this->findModel($id);
        return $this->render('tree', ['tree' => Task::getTree($model->body)]);
    }

    public function actionSaveresult($id) {
        $model = $this->findModel($id);
        $code = $model->begin . $model->body . $model->end;
        $res = Task::run($code);
        if (isset($res['result'])) {
            $model->result = $res['result'];
            if ($model->save())
                Yii::$app->session->setFlash('success', "Ответ сохранен.");
        } else
            Yii::$app->session->setFlash('warning', "Ошибка сохранения.");
        return $this->redirect(['view', 'id' => $model->id]); //$this->render('test', \yii\helpers\ArrayHelper::merge(['model' => $model], $res));            
    }

    public function actionDecide($id) {
        $model = $this->findModel($id);


        $user_task = UserTask::findOne(['task_id' => $id, 'user_id' => Yii::$app->user->id]);
        if (!isset($user_task)) {
            $user_task = new UserTask();
            $user_task->task_id = $id;
            $user_task->user_id = Yii::$app->user->id;
        }
        if (isset($_POST['code'])) {
            $user_task->code = $_POST['code'];
            $res = Task::run($model->begin . $_POST['code'] . $model->end);
            if ($res['result'] && $res['compile_res'] == 0) {
                if ($model->checktype == 0) {
                    if ($model->result)
                        if (strpos(trim($res['result']), $model->result) !== false) {
                            Yii::$app->session->setFlash('success', "Задача решена правильно.");
                            $user_task->is_correct = '1';
                        } else {
                            Yii::$app->session->setFlash('warning', 'Задача решена не верно.');
                            $user_task->is_correct = '0';
                        }
                    $user_task->save();
                    return $this->render('decide', ['model' => $model, 'user_task' => $user_task, 'res' => $res]);
                } else {
                    $res2 = $model->check($model->begin . $_POST['code'] . $model->end);
                    $true_count = 0;
                    foreach ($res2 as $item)
                        if ($item['decided'])
                            $true_count++;
                    if ($true_count == count($res2)) {
                        Yii::$app->session->setFlash('success', 'Задача решена правильно.');
                        $user_task->is_correct = '1';
                    } else {
                        Yii::$app->session->setFlash('warning', 'Задача решена не верно.');
                        $user_task->is_correct = '0';
                    }
                    $user_task->save();
                    return $this->render('decide', ['model' => $model, 'user_task' => $user_task, 'res' => $res, 'res2_all' => $res2]);
                }
            } else {
                $user_task->is_correct = '0';
                $user_task->save();
                Yii::$app->session->setFlash('danger', 'Ошибка компиляции.');
                return $this->render('decide', ['model' => $model, 'user_task' => $user_task, 'res' => $res]);
            }
        } else
            return $this->render('decide', ['model' => $model, 'user_task' => $user_task]);
    }

    public function actionCheck($id) {
        $model = $this->findModel($id);
        $res = $model->check();
        return $this->render('view', ['model' => $model, 'res' => $res]);
    }

    public function actionStudents() {
        $dataProvider = new \yii\data\ActiveDataProvider([
            'query' => \webvimark\modules\UserManagement\models\User::find()->joinWith(['roles'])->where([Yii::$app->getModule('user-management')->auth_item_table . '.name' => 'student']),
        ]);
        return $this->render('students', ['dataProvider' => $dataProvider]);
    }

    public function actionStudent($id) {
        $models = UserTask::findAll(['user_id' => $id]);
        return $this->render('student', ['model' => User::findOne($id), 'tasks' => $models]);
    }

    public function actionTestStudentTask($id, $student_id) {
        $model = $this->findModel($id);
        $student = User::findOne($student_id);

        $user_task = UserTask::findOne(['task_id' => $id, 'user_id' => $student_id]);

        if (isset($_POST['code'])) {
            //$user_task->code = $_POST['code'];
            $res = Task::run($model->begin . $_POST['code'] . $model->end);
            if ($res['result'] && $res['compile_res'] == 0) {
                if ($model->checktype == 0) {
                    if ($model->result)
                        if (strpos(trim($res['result']), $model->result) !== false) {
                            Yii::$app->session->setFlash('success', "Задача решена правильно.");
                            //$user_task->is_correct = '1';
                        } else {
                            Yii::$app->session->setFlash('warning', 'Задача решена не верно.');
                            //$user_task->is_correct = '0';
                        }
                    //$user_task->save();
                    return $this->render('decide', ['model' => $model, 'user_task' => $user_task, 'res' => $res]);
                } else {
                    $res2 = $model->check($model->begin . $_POST['code'] . $model->end);
                    $true_count = 0;
                    foreach ($res2 as $item)
                        if ($item['decided'])
                            $true_count++;
                    if ($true_count == count($res2)) {
                        Yii::$app->session->setFlash('success', 'Задача решена правильно.');
                        //$user_task->is_correct = '1';
                    } else {
                        Yii::$app->session->setFlash('warning', 'Задача решена не верно.');
                        //$user_task->is_correct = '0';
                    }
                    //$user_task->save();
                    return $this->render('decide', ['model' => $model, 'user_task' => $user_task, 'res' => $res, 'res2_all' => $res2]);
                }
            } else {
                //$user_task->is_correct = '0';

views/task/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\models\Category;

/* @var $this yii\web\View */
/* @var $model app\models\Task */
/* @var $form yii\widgets\ActiveForm */
$this->registerJsFile('/js/ace-builds/src-noconflict/ace.js');

$jsScript2 = 'var editor1 = ace.edit("editor1");
    editor1.setTheme("ace/theme/chrome");
    editor1.setOption("minLines", 10);
    editor1.setOption("maxLines", 50);
    editor1.setAutoScrollEditorIntoView(true);   
    document.getElementById("editor1").style.fontSize="14px";
    editor1.getSession().setMode("ace/mode/c_cpp");
    var editor2 = ace.edit("editor2");
    editor2.setTheme("ace/theme/chrome");
    editor2.setOption("minLines", 10);
    editor2.setOption("maxLines", 50);
    editor2.setAutoScrollEditorIntoView(true);   
    document.getElementById("editor2").style.fontSize="14px";
    editor2.getSession().setMode("ace/mode/c_cpp");
    var editor3 = ace.edit("editor3");
    editor3.setTheme("ace/theme/chrome");
    editor3.setOption("minLines", 10);
    editor3.setOption("maxLines", 50);
    editor3.setAutoScrollEditorIntoView(true);   
    document.getElementById("editor3").style.fontSize="14px";
    editor3.getSession().setMode("ace/mode/c_cpp");
    
    editor1.on("change", function(){
        $("#code1").html(editor1.getValue());
    });
    editor2.on("change", function(){
        $("#code2").html(editor2.getValue());
    });
    editor3.on("change", function(){
        $("#code3").html(editor3.getValue());
    });
';

$jsScript = " 
    $('body').on('click', '.add-var', function(){
        $('.vars').append($('.default-var').html());
    });
    $('body').on('click', '.del-var', function(){
        $(this).parent().parent().remove();
    });
    $('body').on('change', '#task-checktype', function(){
        if($(this).val() == 1)
            $('.vars-check').removeClass('hidden');
        else
            $('.vars-check').addClass('hidden');
    });
    ";
$this->registerJs($jsScript);
$this->registerJs($jsScript2);
?>

<div class="task-form">
    <div class="hidden default-var">
        <div class="row">
            <div class="col-md-3"><?= Html::dropDownList('vartype[]', null, [1 => 'int', 2 => 'float'], ['class' => 'form-control']) ?></div>
            <div class="col-md-3"><?= Html::input('text', 'varname[]', '', ['class' => 'form-control']) ?></div>
            <div class="col-md-5"><?= Html::input('text', 'varparam[]', '', ['class' => 'form-control']) ?></div>
            <div class="col-md-1"><div class="btn btn-danger btn-xs pull-left del-var"><span class="glyphicon glyphicon-remove"></span></div></div>
        </div>
    </div>
<?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'name')->textInput(['maxlength' => 255]) ?>
            <?= $form->field($model, 'category_id')->dropDownList(yii\helpers\ArrayHelper::map(Category::find()->all(), 'id', 'name')) ?>   
            <?= $form->field($model, 'begin')->textarea(['rows' => 5, 'id'=>'code1', 'class' => 'hidden']) ?>
            <?= Html::tag('div', Html::encode($model->begin), ['id' => 'editor1', 'class' => 'form-control'])?>
            <?= $form->field($model, 'body')->textarea(['rows' => 5, 'id' => 'code2', 'class' => 'hidden']) ?>
            <?= Html::tag('div', Html::encode($model->body), ['id' => 'editor2', 'class' => 'form-control'])?>
            <?= $form->field($model, 'end')->textarea(['rows' => 5, 'id' => 'code3', 'class' => 'hidden']) ?> 
            <?= Html::tag('div', Html::encode($model->end), ['id' => 'editor3', 'class' => 'form-control'])?>
            
            
            
                       
        </div>
        <div class="col-md-6">
            <?= $form->field($model, 'description')->textarea(['rows' => 5]) ?>
            <?= $form->field($model, 'checktype')->dropDownList($model->getChecktypes()) ?>  
            <div class="panel panel-primary vars-check <?= $model->checktype==1?'':'hidden'?>">
                <div class="panel-body">
                    <h4>Добавьте переменных для перебора.</h4>
                    <h5 class="subheader"></h5>
                    <div class="vars">
                        <div class="row">
                            <div class="col-md-3"><?= Html::label('Тип', ['class' => 'control-label'])?></div>
                            <div class="col-md-3"><?= Html::label('Имя', ['class' => 'control-label'])?></div>                            
                            <div class="col-md-6"><?= Html::label('Параметры(min; max)', ['class' => 'control-label'])?></div>
                        </div>
                        <?php $vars = json_decode($model->extra, true); if($model->isNewRecord || empty($vars)):?>
                        <div class="row">
                            <div class="col-md-3"><?= Html::dropDownList('vartype[]', null, [1 => 'int', 2 => 'float'], ['class' => 'form-control'])?></div>
                            <div class="col-md-3"><?= Html::input('text', 'varname[]','', ['class' => 'form-control'])?></div>
                            <div class="col-md-5"><?= Html::input('text', 'varparam[]','', ['class' => 'form-control'])?></div>
                            <div class="col-md-1"><div class="btn btn-danger btn-xs pull-left del-var"><span class="glyphicon glyphicon-remove"></span></div></div>
                        </div>
                        <?php else: ?>
                        <?php for($i=0; $i<count($vars['varname']); $i++):?>
                        <div class="row">
                            <div class="col-md-3"><?= Html::dropDownList("vartype[$i]", $vars['vartype'][$i], [1 => 'int', 2 => 'float'], ['class' => 'form-control'])?></div>
                            <div class="col-md-3"><?= Html::input('text', "varname[$i]",$vars['varname'][$i], ['class' => 'form-control'])?></div>
                            <div class="col-md-5"><?= Html::input('text', "varparam[$i]",$vars['varparam'][$i], ['class' => 'form-control'])?></div>
                            <div class="col-md-1"><div class="btn btn-danger btn-xs pull-left del-var"><span class="glyphicon glyphicon-remove"></span></div></div>
                        </div>
                        <?php endfor;?>
                        
                        <?php endif;?>
                    </div>
                    <p>
                        <div class="btn btn-primary add-var"><span class="glyphicon glyphicon-plus"></span></div>
                    </p>
                    
                </div>
              </div>
        </div>
    </div>
    

    <p>
    <div class="form-group">
<?= Html::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить редактирование', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
</p>
<?php ActiveForm::end(); ?>

</div>

views/task/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\TaskSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="task-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'begin') ?>

    <?= $form->field($model, 'body') ?>

    <?php // echo $form->field($model, 'end') ?>

    <?php // echo $form->field($model, 'extra') ?>

    <?php // echo $form->field($model, 'category_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/task/_student.php
<?php

use yii\helpers\Html;
use app\models\UserTask;
?>

<tr>
    <td>
       <?= Html::a($model->username, ['student', 'id' => $model->id])?> 
    </td>
    <td>
        <?= UserTask::getUserTasks($model->id)?>
    </td>
    <td>
        <?= UserTask::getUserTasks($model->id, 1)?>
    </td>
</tr>

views/task/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Task */

$this->title = 'Создание задачи';
$this->params['breadcrumbs'][] = ['label' => 'Задачи', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/task/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\Category;
/* @var $this yii\web\View */
/* @var $searchModel app\models\TaskSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Список задач | Преподаватель';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Создать задачу', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'name',
            [
                'label' => 'Категория',
                'value' => 'category.name',
                'filter' => Html::activeDropDownList($searchModel, 'category_id', ArrayHelper::map(Category::find()->all(), 'id', 'name'), ['prompt' => 'Без категории', 'class' => 'form-control']),                
            ],
            'description:ntext',
            //'begin:ntext',
            //'body:ntext',
            // 'end:ntext',
            // 'extra:ntext',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{test}{view}{update}{delete}',
                'buttons' => [
                    'test' => function($url, $model){
                        return Html::a('Проверить', Yii::$app->getUrlManager()->createUrl(['task/test', 'id'=>$model->id]), ['class' => 'btn btn-xs btn-success']);

                    },
                    'tree' => function($url, $model){
                        return Html::a('Дерево', Yii::$app->getUrlManager()->createUrl(['task/tree', 'id'=>$model->id]), ['class' => 'btn btn-xs btn-success']);

                    }
                ],
            ],
        ],
    ]); ?>

</div>

views/task/list.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;
use app\models\Category;
/* @var $this yii\web\View */
/* @var $searchModel app\models\TaskSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Список задач | Ученик';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="task-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,        
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'id',
            'name',
            [
                'label' => 'Категория',
                'value' => 'category.name',
                'filter' => Html::activeDropDownList($searchModel, 'category_id', ArrayHelper::merge([null => 'Без категории'], ArrayHelper::map(Category::find()->all(), 'id', 'name')), ['class'=>'form-control']),                
            ],
            'description:ntext',
            [
                'label' => 'Статус',
                'format' => 'raw',
                'value' => function($model){
                    $task = $model->getUserTask();
                    if(isset($task))
                        if($task->is_correct=='1')
                            return 'Задача решена правильно.';
                        else
                            return '<label class="text-danger">Задача решена не правильно.</label>';
                    else
                        return '';
                            
                }
            ],
            [
                'class' => 'yii\grid\ActionColumn',
                'buttons' => [
                    'decide' => function($url, $model){
                        $task = $model->getUserTask();
                    if(isset($task))
                        if($task->is_correct=='1')
                            return Html::a('Просмотреть', Yii::$app->getUrlManager()->createUrl(['task/decide', 'id'=>$model->id]), ['class' => 'btn btn-sm btn-primary']);
                        else
                            return Html::a('Просмотреть', Yii::$app->getUrlManager()->createUrl(['task/decide', 'id'=>$model->id]), ['class' => 'btn btn-sm btn-danger']);
                    else
                        return Html::a('Решить', Yii::$app->getUrlManager()->createUrl(['task/decide', 'id'=>$model->id]), ['class' => 'btn btn-sm btn-success']);
                    }
                ],
                'template' => '{decide}',
            ],
        ],
    ]); ?>

</div>

views/task/test.php
<?php 
use yii\helpers\Html;
$this->title = "Проверка задачи ".$model->name;
$this->params['breadcrumbs'][] = ['label' => 'Задачи', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Решение';

?>
<p>
    <?= Html::a('Создать задачу', ['create'], ['class' => 'btn btn-success']) ?>  
    <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
</p>

<div class="panel panel-info">
  <div class="panel-heading">
    <h3 class="panel-title">Задача: <?=$model->name?></h3>
  </div>
  <div class="panel-body">
      <p><?=$model->description?></p>
      <?php if($model->result):?>
      <h4>
          Ответ: <mark><?= $model->result?></mark>
      </h4>
      <?php endif;?>
      <div>
          <p><span class="label label-default">Исходный код</span></p>
          <pre><?= Html::encode($model->begin.$model->body.$model->end)?></pre>
      </div>
  </div>
</div>
<?php if($compile_res !== 0):?>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Результат компиляции</h3>
  </div>
  <div class="panel-body">
      <p><span class="label label-primary">Код возврата: <?=$compile_res?></span></p>
      <pre><?= $compile ?></pre>    
  </div>
</div>
<?php endif;?>
<?php if (!empty($result)): ?>
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">Результат выполнения</h3>
  </div>
  <div class="panel-body">
      <pre><?= $result ?></pre>
      <?= Html::a('Сохранить ответ', ['task/saveresult', 'id' => $model->id], ['class' => 'btn btn-success'])?>
  </div>
</div>
<?php endif; ?>

views/task/tree.php
<?php
use yii\helpers\Html;

?>

<pre>
    <?php print_r($tree);?>
</pre>